import {
  FolderOpenIcon,
  Rocket01Icon,
  CodeIcon,
  Database01Icon,
  HardDriveIcon,
  Share08Icon,
  FlashIcon,
  Clock01Icon,
  Mail01Icon,
  GlobalIcon,
  Activity01Icon,
  File01Icon,
  Robot02Icon,
  ShoppingCart01Icon,
  LockPasswordIcon,
  Settings01Icon,
} from '@hugeicons/core-free-icons';

type Tool = { name: string; desc: string; example?: string };

type IconType = typeof FolderOpenIcon;

export type ServiceGroup = {
  title: string;
  icon: IconType;
  color: string;
  desc: string;
  tools: Tool[];
};

export const SERVICE_GROUPS: ServiceGroup[] = [
  {
    title: 'Projects',
    icon: FolderOpenIcon,
    color: 'text-yellow-400',
    desc: 'Create and manage projects.',
    tools: [
      { name: 'project_list', desc: 'List all your projects.', example: 'sdk.projects.list()' },
      { name: 'project_create', desc: 'Create a new project.', example: "sdk.projects.create({ name: 'my-app', type: 'frontend' })" },
    ],
  },
  {
    title: 'Deployments',
    icon: Rocket01Icon,
    color: 'text-blue-400',
    desc: 'Build and deploy your application from a Git repository.',
    tools: [
      { name: 'deployments_list', desc: 'List all deployments for a project.', example: 'sdk.deployments.list(projectId)' },
      { name: 'deployments_get', desc: 'Get a deployment status and logs.', example: 'sdk.deployments.get(projectId, deploymentId)' },
      { name: 'deployments_getLogs', desc: 'Stream live build and runtime logs.', example: 'sdk.deployments.getLogs(projectId, deploymentId)' },
      { name: 'deployments_create', desc: 'Trigger a new deployment from a Git branch.', example: "sdk.deployments.create(projectId, { branch: 'main' })" },
      { name: 'deployments_stop', desc: 'Stop a running deployment.', example: 'sdk.deployments.stop(projectId, deploymentId)' },
      { name: 'deployments_restart', desc: 'Restart a deployment.', example: 'sdk.deployments.restart(projectId, deploymentId)' },
      { name: 'deployments_rollback', desc: 'Rollback to a previous deployment.', example: 'sdk.deployments.rollback(projectId, deploymentId)' },
      { name: 'deployments_destroy', desc: 'Permanently destroy a deployment.', example: 'sdk.deployments.destroy(projectId, deploymentId)' },
    ],
  },
  {
    title: 'Functions',
    icon: CodeIcon,
    color: 'text-green-400',
    desc: 'Serverless edge functions in Node.js or Python.',
    tools: [
      { name: 'functions_list', desc: 'List all functions in a project.', example: 'sdk.functions.list(projectId)' },
      { name: 'functions_get', desc: 'Get function details and invocations.', example: 'sdk.functions.get(projectId, functionId)' },
      { name: 'functions_create', desc: 'Create a new function.', example: "sdk.functions.create(projectId, { name: 'my-fn', runtime: 'nodejs20' })" },
      { name: 'functions_deploy', desc: 'Deploy code to a function.', example: "sdk.functions.deploy(projectId, functionId, { code: fs.readFileSync('handler.js') })" },
      { name: 'functions_update', desc: 'Update function configuration.', example: 'sdk.functions.update(projectId, functionId, { memory: 256 })' },
      { name: 'functions_delete', desc: 'Delete a function.', example: 'sdk.functions.delete(projectId, functionId)' },
      { name: 'functions_invoke', desc: 'Invoke a function synchronously.', example: "sdk.functions.invoke(projectId, functionId, { name: 'Alice' })" },
    ],
  },
  {
    title: 'Databases',
    icon: Database01Icon,
    color: 'text-purple-400',
    desc: 'PostgreSQL with connection pooling, automated backups, and point-in-time restore.',
    tools: [
      { name: 'databases_list', desc: 'List all databases.', example: 'sdk.databases.list(projectId)' },
      { name: 'databases_get', desc: 'Get database connection details.', example: 'sdk.databases.get(databaseId)' },
      { name: 'databases_create', desc: 'Create a new database.', example: "sdk.databases.create(projectId, { name: 'my-db' })" },
      { name: 'databases_delete', desc: 'Delete a database permanently.', example: 'sdk.databases.delete(databaseId)' },
      { name: 'databases_backup', desc: 'Trigger a manual backup.', example: 'sdk.databases.backup(databaseId)' },
      { name: 'databases_listBackups', desc: 'List available backups.', example: 'sdk.databases.listBackups(databaseId)' },
      { name: 'databases_restore', desc: 'Restore from a backup.', example: 'sdk.databases.restore(databaseId, backupId)' },
    ],
  },
  {
    title: 'Storage',
    icon: HardDriveIcon,
    color: 'text-orange-400',
    desc: 'S3-compatible object storage. Upload, download, list files, and generate signed URLs.',
    tools: [
      { name: 'storage_listBuckets', desc: 'List all storage buckets.', example: 'sdk.storage.listBuckets(projectId)' },
      { name: 'storage_createBucket', desc: 'Create a storage bucket.', example: "sdk.storage.createBucket(projectId, 'assets')" },
      { name: 'storage_deleteBucket', desc: 'Delete a bucket and all its contents.', example: 'sdk.storage.deleteBucket(bucketId)' },
      { name: 'storage_listFiles', desc: 'List files in a bucket.', example: 'sdk.storage.listFiles(projectId, bucketId)' },
      { name: 'storage_uploadFile', desc: 'Upload a file to a bucket.', example: "sdk.storage.uploadFile(projectId, bucketId, 'uploads/image.png', fileBuffer)" },
      { name: 'storage_deleteFile', desc: 'Delete a file from a bucket.', example: 'sdk.storage.deleteFile(projectId, bucketId, fileId)' },
      { name: 'storage_getSignedUrl', desc: 'Generate a time-limited signed URL for private files.', example: 'sdk.storage.getSignedUrl(projectId, bucketId, fileId, 3600)' },
    ],
  },
  {
    title: 'Queues',
    icon: Share08Icon,
    color: 'text-cyan-400',
    desc: 'Durable message queues with at-least-once delivery, dead-letter queues, and retry policies.',
    tools: [
      { name: 'queues_list', desc: 'List all queues.', example: 'sdk.queues.list(projectId)' },
      { name: 'queues_get', desc: 'Get queue stats and configuration.', example: 'sdk.queues.get(projectId, queueId)' },
      { name: 'queues_create', desc: 'Create a new queue.', example: "sdk.queues.create(projectId, { name: 'email-jobs', type: 'work' })" },
      { name: 'queues_delete', desc: 'Delete a queue and all messages.', example: 'sdk.queues.delete(projectId, queueId)' },
      { name: 'queues_publish', desc: 'Publish a message to a queue.', example: "sdk.queues.publish(projectId, queueId, { to: 'user@example.com', body: 'Hello' })" },
      { name: 'queues_getMessages', desc: 'Consume messages from a queue (auto-acks on success).', example: 'sdk.queues.getMessages(projectId, queueId, { maxMessages: 10 })' },
    ],
  },
  {
    title: 'Scheduler',
    icon: Clock01Icon,
    color: 'text-pink-400',
    desc: 'Cron jobs that survive server restarts. Trigger HTTP endpoints, queue jobs, or run custom code.',
    tools: [
      { name: 'cron_list', desc: 'List all cron jobs.', example: 'sdk.cron.list(projectId)' },
      { name: 'cron_get', desc: 'Get a cron job with its schedule and recent runs.', example: 'sdk.cron.get(projectId, jobId)' },
      { name: 'cron_create', desc: 'Create a cron job.', example: "sdk.cron.create(projectId, { name: 'daily-report', schedule: '0 9 * * *', endpoint: 'https://...' })" },
      { name: 'cron_update', desc: 'Update schedule or endpoint.', example: "sdk.cron.update(projectId, jobId, { schedule: '0 10 * * *' })" },
      { name: 'cron_delete', desc: 'Delete a cron job.', example: 'sdk.cron.delete(projectId, jobId)' },
      { name: 'cron_trigger', desc: 'Fire a cron job immediately (skip the schedule).', example: 'sdk.cron.trigger(projectId, jobId)' },
      { name: 'cron_getNextRun', desc: 'Preview the next N scheduled executions.', example: 'sdk.cron.getNextRun(projectId, jobId)' },
    ],
  },
  {
    title: 'Email',
    icon: Mail01Icon,
    color: 'text-indigo-400',
    desc: 'Transactional email via Stalwart SMTP. Send from your own domain with DKIM signing.',
    tools: [
      { name: 'email_status', desc: 'Get email domain verification status (DKIM, SPF, DMARC, MX).', example: 'sdk.email.status(projectId, domainId)' },
      { name: 'email_domains', desc: 'List connected email domains.', example: 'sdk.email.domains(projectId)' },
      { name: 'email_send', desc: 'Send a transactional email.', example: "sdk.email.send(projectId, { from: 'app@domain.com', to: 'user@domain.com', subject: 'Hello', text: 'Hi there' })" },
      { name: 'email_send_template', desc: 'Send an email using a saved template.', example: "sdk.email.sendTemplate(projectId, { templateId: 'welcome', to: 'user@domain.com' })" },
      { name: 'email_templates', desc: 'List saved email templates.', example: 'sdk.email.templates(projectId)' },
      { name: 'email_inbox', desc: 'List messages in an inbox (IMAP).', example: "sdk.email.inbox(projectId, { mailboxId: 'inbox', limit: 20 })" },
      { name: 'email_analytics', desc: 'Get email delivery statistics (open rate, click rate, bounces).', example: 'sdk.email.analytics(projectId)' },
      { name: 'email_suppressions', desc: 'List suppressed (bounced/complained) addresses.', example: 'sdk.email.suppressions(projectId)' },
    ],
  },
  {
    title: 'Domains',
    icon: GlobalIcon,
    color: 'text-teal-400',
    desc: 'Custom domains with automatic TLS via Cloudflare and Traefik.',
    tools: [
      { name: 'domain_list', desc: 'List all domains.', example: 'sdk.domains.list(projectId)' },
      { name: 'domain_add', desc: 'Add a custom domain to a project.', example: "sdk.domains.create(projectId, 'app.example.com')" },
      { name: 'domain_verify', desc: 'Verify domain DNS configuration (DKIM, MX, TXT records).', example: 'sdk.domains.verify(projectId, domainId)' },
    ],
  },
  {
    title: 'Realtime',
    icon: FlashIcon,
    color: 'text-amber-400',
    desc: 'WebSocket channels for live UI updates, presence indicators, and collaborative features.',
    tools: [
      { name: 'realtime_listChannels', desc: 'List all active channels.', example: 'sdk.realtime.listChannels(projectId)' },
      { name: 'realtime_createChannel', desc: 'Create a named channel.', example: "sdk.realtime.createChannel(projectId, { name: 'live-updates' })" },
      { name: 'realtime_deleteChannel', desc: 'Delete a channel and all subscribers.', example: 'sdk.realtime.deleteChannel(projectId, channelId)' },
      { name: 'realtime_setPresence', desc: 'Broadcast a presence update (online/away/typing).', example: "sdk.realtime.setPresence(projectId, channelId, { userId: '123', status: 'typing' })" },
    ],
  },
  {
    title: 'Monitoring',
    icon: Activity01Icon,
    color: 'text-red-400',
    desc: 'Uptime checks, alert rules, dashboards, and Pagerduty/Slack notifications.',
    tools: [
      { name: 'monitoring_getActiveAlerts', desc: 'List currently firing alerts.', example: 'sdk.monitoring.getActiveAlerts(projectId)' },
      { name: 'monitoring_listAlertRules', desc: 'List all alert rules.', example: 'sdk.monitoring.listAlertRules(projectId)' },
      { name: 'monitoring_getAlertRule', desc: 'Get a specific alert rule.', example: 'sdk.monitoring.getAlertRule(projectId, ruleId)' },
      { name: 'monitoring_createAlertRule', desc: 'Create an alert rule (e.g., CPU > 80% for 5 min).', example: "sdk.monitoring.createAlertRule(projectId, { name: 'High CPU', metric: 'cpu_usage', threshold: 80 })" },
      { name: 'monitoring_updateAlertRule', desc: 'Update an alert rule threshold or notification channel.', example: 'sdk.monitoring.updateAlertRule(projectId, ruleId, { threshold: 90 })" ' },
      { name: 'monitoring_deleteAlertRule', desc: 'Delete an alert rule.', example: 'sdk.monitoring.deleteAlertRule(projectId, ruleId)' },
      { name: 'monitoring_acknowledgeAlert', desc: 'Acknowledge an active alert (stops it from paging).', example: 'sdk.monitoring.acknowledgeAlert(projectId, alertId)' },
      { name: 'monitoring_resolveAlert', desc: 'Manually resolve an alert.', example: 'sdk.monitoring.resolveAlert(projectId, alertId)' },
      { name: 'monitoring_getMetrics', desc: 'Query metric time series data.', example: "sdk.monitoring.getMetrics(projectId, { metric: 'cpu_usage', from: Date.now() - 3600000 })" },
      { name: 'monitoring_getMetricsStats', desc: 'Get min/max/avg/percentiles over a time window.', example: "sdk.monitoring.getMetricsStats(projectId, { metric: 'memory_usage', window: '1h' })" },
      { name: 'monitoring_listDashboards', desc: 'List metric dashboards.', example: 'sdk.monitoring.listDashboards(projectId)' },
      { name: 'monitoring_createDashboard', desc: 'Create a custom dashboard.', example: "sdk.monitoring.createDashboard(projectId, { name: 'Production', panels: [...] })" },
      { name: 'monitoring_listNotificationChannels', desc: 'List notification channels (email, Slack, Pagerduty).', example: 'sdk.monitoring.listNotificationChannels(projectId)' },
      { name: 'monitoring_createNotificationChannel', desc: 'Add a notification channel.', example: "sdk.monitoring.createNotificationChannel(projectId, { type: 'slack', url: 'https://hooks.slack.com/...' })" },
      { name: 'monitoring_getUptime', desc: 'Get uptime percentage over time.', example: 'sdk.monitoring.getUptime(projectId)' },
      { name: 'monitoring_recordMetric', desc: 'Ingest a custom metric data point.', example: "sdk.monitoring.recordMetric(projectId, { name: 'app.requests', value: 42, tags: { method: 'GET' } })" },
    ],
  },
  {
    title: 'Logging',
    icon: File01Icon,
    color: 'text-lime-400',
    desc: 'Structured log ingestion, querying, and tailing. Ingester available for Fluentd, Vector, and raw HTTP.',
    tools: [
      { name: 'logging_listLogStreams', desc: 'List all log streams.', example: 'sdk.logging.listLogStreams(projectId)' },
      { name: 'logging_getLogStream', desc: 'Get stream configuration.', example: 'sdk.logging.getLogStream(projectId, streamId)' },
      { name: 'logging_createLogStream', desc: 'Create a new log stream.', example: "sdk.logging.createLogStream(projectId, { name: 'nginx', destination: 'loki' })" },
      { name: 'logging_deleteLogStream', desc: 'Delete a log stream.', example: 'sdk.logging.deleteLogStream(projectId, streamId)' },
      { name: 'logging_queryLogs', desc: 'Query logs with a PromQL-style filter.', example: "sdk.logging.queryLogs(projectId, { filter: '{app=\"api\"} |= \"error\"', limit: 100 })" },
      { name: 'logging_tailLogs', desc: 'Stream new log entries as they arrive (SSE).', example: "sdk.logging.tailLogs(projectId, streamId)" },
      { name: 'logging_getLogEvents', desc: 'Fetch log events for a stream.', example: 'sdk.logging.getLogEvents(projectId, streamId, { from: Date.now() - 86400000 })' },
      { name: 'logging_getLogStats', desc: 'Get log volume statistics.', example: "sdk.logging.getLogStats(projectId, { window: '24h' })" },
      { name: 'logging_ingestLogs', desc: 'Ingest raw log lines via HTTP (no agent needed).', example: "sdk.logging.ingestLogs(projectId, streamId, { logs: ['2024-01-01 GET /api 200 5ms'] })" },
      { name: 'logging_createLogIngester', desc: 'Create an ingester (HTTP, Fluentd, Vector).', example: "sdk.logging.createLogIngester(projectId, { type: 'http', url: 'https://...' })" },
    ],
  },
  {
    title: 'AI',
    icon: Robot02Icon,
    color: 'text-violet-400',
    desc: 'AI-powered deployment assist, error diagnosis, and code generation from your project context.',
    tools: [
      { name: 'ai_assistDeployment', desc: 'Get AI assistance while creating a deployment.', example: "sdk.ai.assistDeployment(projectId, { branch: 'main' })" },
      { name: 'ai_diagnoseIssue', desc: 'Describe an error and get a root cause analysis.', example: "sdk.ai.diagnoseIssue(projectId, { errorMessage: 'Connection refused' })" },
      { name: 'ai_explainError', desc: 'Get a plain-English explanation of a runtime error.', example: "sdk.ai.explainError(projectId, { logSnippet: 'TypeError: Cannot read property' })" },
      { name: 'ai_generateTemplate', desc: 'Generate project scaffolding from a description.', example: "sdk.ai.generateTemplate({ description: 'Next.js with PostgreSQL and Redis' })" },
      { name: 'ai_listConversations', desc: 'List AI diagnostic conversations.', example: 'sdk.ai.listConversations(projectId)' },
      { name: 'ai_getConversation', desc: 'Get a specific AI conversation thread.', example: 'sdk.ai.getConversation(projectId, conversationId)' },
      { name: 'ai_createConversation', desc: 'Start a new AI diagnostic conversation.', example: "sdk.ai.createConversation(projectId, { title: 'Deployment issue' })" },
      { name: 'ai_sendChatMessage', desc: 'Send a message in an AI conversation.', example: "sdk.ai.sendChatMessage(projectId, conversationId, { message: 'Build failed with exit code 1' })" },
      { name: 'ai_recommendSolution', desc: 'Get a recommended fix for a known error pattern.', example: "sdk.ai.recommendSolution(projectId, { errorPattern: 'ECONNREFUSED' })" },
      { name: 'ai_suggestFix', desc: 'Get a suggested code fix for a failing function.', example: "sdk.ai.suggestFix(functionId, { error: 'ReferenceError: x is not defined' })" },
    ],
  },
  {
    title: 'Marketplace',
    icon: ShoppingCart01Icon,
    color: 'text-emerald-400',
    desc: 'Template marketplace. Browse, submit, and review deployable project templates.',
    tools: [
      { name: 'marketplace_browse', desc: 'Browse available templates.', example: 'sdk.marketplace.browse({ category: "frontend", limit: 20 })' },
      { name: 'marketplace_search', desc: 'Search templates by keyword.', example: "sdk.marketplace.search('Next.js postgres')" },
      { name: 'marketplace_getTemplateDetails', desc: 'Get a template README, stack, and requirements.', example: 'sdk.marketplace.getTemplateDetails(templateId)' },
      { name: 'marketplace_getFeatured', desc: 'Get featured templates for the homepage.', example: 'sdk.marketplace.getFeatured()' },
      { name: 'marketplace_listCategories', desc: 'List all template categories.', example: 'sdk.marketplace.listCategories()' },
      { name: 'marketplace_listMySubmissions', desc: 'List your submitted templates.', example: 'sdk.marketplace.listMySubmissions(projectId)' },
      { name: 'marketplace_submitItem', desc: 'Submit a project as a template to the marketplace.', example: 'sdk.marketplace.submitItem(projectId, { description: "My template" })' },
      { name: 'marketplace_updateSubmission', desc: 'Update a submitted template.', example: 'sdk.marketplace.updateSubmission(submissionId, { description: "Updated" })' },
      { name: 'marketplace_submitReview', desc: 'Submit a review for a template.', example: "sdk.marketplace.submitReview(templateId, { rating: 5, comment: 'Great template!' })" },
    ],
  },
  {
    title: 'Auth',
    icon: LockPasswordIcon,
    color: 'text-sky-400',
    desc: 'Sessions, organizations, teams, and user invitations.',
    tools: [
      { name: 'auth_verify_email', desc: 'Verify a user email address.', example: 'sdk.auth.verifyEmail(token)' },
      { name: 'auth_send_verification', desc: 'Resend an email verification link.', example: "sdk.auth.sendVerification('user@example.com')" },
      { name: 'auth_reset_password', desc: 'Initiate a password reset email.', example: "sdk.auth.resetPassword('user@example.com')" },
      { name: 'auth_list_sessions', desc: 'List all active sessions for the current user.', example: 'sdk.auth.listSessions()' },
      { name: 'auth_revoke_session', desc: 'Revoke a specific session (force logout).', example: 'sdk.auth.revokeSession(sessionId)' },
      { name: 'auth_revoke_all_sessions', desc: 'Revoke all sessions for the current user.', example: 'sdk.auth.revokeAllSessions()' },
      { name: 'auth_list_organizations', desc: 'List organizations the user belongs to.', example: 'sdk.auth.listOrganizations()' },
      { name: 'auth_create_organization', desc: 'Create a new organization.', example: "sdk.auth.createOrganization({ name: 'Acme Corp' })" },
      { name: 'auth_get_organization', desc: 'Get organization details and member count.', example: 'sdk.auth.getOrganization(orgId)' },
      { name: 'auth_list_org_members', desc: 'List members of an organization.', example: 'sdk.auth.listOrgMembers(orgId)' },
      { name: 'auth_list_org_teams', desc: 'List teams within an organization.', example: 'sdk.auth.listOrgTeams(orgId)' },
      { name: 'auth_create_team', desc: 'Create a team within an organization.', example: "sdk.auth.createTeam(orgId, { name: 'Engineering' })" },
      { name: 'auth_invite_user', desc: 'Invite a user to an organization or team.', example: "sdk.auth.inviteUser({ email: 'dev@acme.com', role: 'developer' })" },
      { name: 'auth_accept_invitation', desc: 'Accept a pending invitation.', example: 'sdk.auth.acceptInvitation(invitationId)' },
    ],
  },
  {
    title: 'Environment Variables',
    icon: Settings01Icon,
    color: 'text-gray-400',
    desc: 'Per-environment key-value secrets injected at runtime.',
    tools: [
      { name: 'env_var_list', desc: 'List all environment variables for a project.', example: 'sdk.env.list(projectId)' },
      { name: 'env_var_set', desc: 'Set or update an environment variable.', example: "sdk.env.set(projectId, 'DATABASE_URL', 'postgres://...')" },
      { name: 'env_var_delete', desc: 'Delete an environment variable.', example: "sdk.env.delete(projectId, 'OLD_SECRET')" },
    ],
  },
];

export const CLI_COMMANDS: { group: string; cmds: { cmd: string; desc: string }[] }[] = [
  { group: 'Account', cmds: [{ cmd: 'fidscript login <key>', desc: 'Store your API key' }, { cmd: 'fidscript logout', desc: 'Remove stored credentials' }, { cmd: 'fidscript whoami', desc: 'Show current user' }] },
  { group: 'Projects', cmds: [{ cmd: 'fidscript projects list', desc: 'List all projects' }, { cmd: 'fidscript projects create <name>', desc: 'Create a project' }] },
  { group: 'Deployments', cmds: [{ cmd: 'fidscript deployments list', desc: 'List deployments' }, { cmd: 'fidscript deployments create', desc: 'Trigger a deployment' }, { cmd: 'fidscript deployments logs <id>', desc: 'Stream deployment logs' }, { cmd: 'fidscript deployments stop <id>', desc: 'Stop a deployment' }, { cmd: 'fidscript deployments restart <id>', desc: 'Restart a deployment' }, { cmd: 'fidscript deployments rollback <id>', desc: 'Rollback to previous' }] },
  { group: 'Functions', cmds: [{ cmd: 'fidscript functions list', desc: 'List functions' }, { cmd: 'fidscript functions create', desc: 'Create a function' }, { cmd: 'fidscript functions deploy <id>', desc: 'Deploy function code' }, { cmd: 'fidscript functions logs <id>', desc: 'Tail function logs' }, { cmd: 'fidscript functions invoke <id>', desc: 'Invoke a function' }] },
  { group: 'Databases', cmds: [{ cmd: 'fidscript databases list', desc: 'List databases' }, { cmd: 'fidscript databases create <name>', desc: 'Create a database' }, { cmd: 'fidscript databases backup <id>', desc: 'Trigger a backup' }, { cmd: 'fidscript databases restore <id>', desc: 'Restore from backup' }] },
  { group: 'Storage', cmds: [{ cmd: 'fidscript storage buckets', desc: 'List buckets' }, { cmd: 'fidscript storage create-bucket <name>', desc: 'Create a bucket' }, { cmd: 'fidscript storage upload <bucket> <key> <file>', desc: 'Upload a file' }, { cmd: 'fidscript storage download <bucket> <key>', desc: 'Download a file' }] },
  { group: 'Queues', cmds: [{ cmd: 'fidscript queues list', desc: 'List queues' }, { cmd: 'fidscript queues create <name>', desc: 'Create a queue' }, { cmd: 'fidscript queues publish <name>', desc: 'Publish a message' }, { cmd: 'fidscript queues consume <name>', desc: 'Consume messages' }] },
  { group: 'Cron', cmds: [{ cmd: 'fidscript cron list', desc: 'List cron jobs' }, { cmd: 'fidscript cron create', desc: 'Create a cron job' }, { cmd: 'fidscript cron trigger <id>', desc: 'Trigger a job immediately' }, { cmd: 'fidscript cron delete <id>', desc: 'Delete a cron job' }] },
  { group: 'Email', cmds: [{ cmd: 'fidscript email send', desc: 'Send an email' }, { cmd: 'fidscript email inbox', desc: 'List inbox messages' }, { cmd: 'fidscript email templates', desc: 'List templates' }, { cmd: 'fidscript email status <messageId>', desc: 'Get delivery status' }] },
  { group: 'Domains', cmds: [{ cmd: 'fidscript domains list', desc: 'List domains' }, { cmd: 'fidscript domains create <domain>', desc: 'Add a domain' }, { cmd: 'fidscript domains check-health <id>', desc: 'Run a health check' }] },
  { group: 'Env Vars', cmds: [{ cmd: 'fidscript env list', desc: 'List environment variables' }, { cmd: 'fidscript env set <key> <value>', desc: 'Set a variable' }, { cmd: 'fidscript env delete <key>', desc: 'Delete a variable' }] },
  { group: 'Logs', cmds: [{ cmd: 'fidscript logs tail <service>', desc: 'Tail live logs (Ctrl+C to stop)' }, { cmd: 'fidscript logs query', desc: 'Query logs interactively' }] },
];
