http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

    compress:
      compress: {}

  routers:
    dashboard:
      rule: "Host(`deploy.fidscript.com`)"
      service: dashboard
      middlewares:
        - security-headers
        - compress
      tls:
        certResolver: letsencrypt

    api:
      rule: "PathPrefix(`/api`)"
      service: api
      middlewares:
        - security-headers
        - compress
      tls:
        certResolver: letsencrypt

    minio-console:
      rule: "Host(`storage.fidscript.com`)"
      service: minio-console
      middlewares:
        - security-headers
        - compress
      tls:
        certResolver: letsencrypt

  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://fidscript_dashboard:3000"

    api:
      loadBalancer:
        servers:
          - url: "http://fidscript_api:3001"

    minio-console:
      loadBalancer:
        servers:
          - url: "http://fidscript_minio:9001"